name: Transporter
main: com.frdfsnlght.transporter.Transporter
version: ${project.version}
authors:
  - frdfsnlght
website: http://dev.bukkit.org/server-mods/transporter/
description: >
  Provides teleportation through gates between worlds and servers.
softdepend: [Vault, Inquisitor, PermissionsEx, Dynmap]
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]
